export interface ReferenceIndustryCard {
  title: string;
  description: string;
}

export interface ReferenceIndustryContent {
  tag: string;
  title: string;
  sub: string;
  pain: ReferenceIndustryCard[];
  sol: ReferenceIndustryCard[];
  lawTitle: string;
  laws: string[];
  storyTitle: string;
  story: string;
  cta: string;
}

export const referenceIndustryContent: Record<string, ReferenceIndustryContent> = {
  "restaurant": {
    "tag": "Restaurant & F&B Accounting UAE · Verified UAE Tax Laws 2026", "title": "Restaurants & F&B, VAT, POS Reconciliation & Cost Control", "sub": "Running a restaurant in UAE means managing VAT across dine-in, takeaway, delivery platforms, and staff meals, each with distinct rules under UAE VAT Law. One wrong classification and you have an FTA liability building quietly every quarter. BookLean has handled VAT and accounting for 80+ UAE restaurants and cafés since VAT was introduced in 2018.", "pain": [
      {
        "title": "POS Data Never Matches the Books", "description": "Talabat, Careem, Deliveroo, Zomato, every platform has different settlement cycles, commission structures, and VAT treatment on their fees. Most restaurants carry an unexplained monthly gap between POS revenue and accounting records. This is exactly what FTA auditors look for first."
      }, {
        "title": "Staff Meals, Deemed Supply Rule Ignored", "description": "Under UAE VAT Law and FTA Public Clarification VATP005, providing meals free of charge to employees is a \"deemed supply.\" Output VAT must be accounted for on the cost of those meals. Most F&B businesses apply no VAT here and quietly accumulate a liability that compounds every quarter."
      }, {
        "title": "Food Cost & Margin Blind Spots", "description": "Most restaurant owners do not know their true food cost percentage until month-end, and by then it is too late to act. Without real-time cost tracking per outlet, you are making pricing and purchasing decisions on assumptions rather than facts."
      }, {
        "title": "Multi-Outlet VAT Returns Filed Incorrectly", "description": "A single VAT registration covers all outlets, but returns aggregated across locations without outlet-level reconciliation contain errors the FTA can identify. Inter-outlet transfers and recharges also carry their own VAT treatment that most multi-location groups get wrong."
      }
    ], "sol": [
      {
        "title": "POS-to-Accounts Reconciliation Monthly", "description": "We reconcile every delivery platform, Talabat, Noon, Zomato, Deliveroo, Careem, against your bank statement and accounting records. One clean, FTA-ready set of books. Zero unexplained gaps."
      }, {
        "title": "Correct VAT on Every Transaction", "description": "We apply the right UAE VAT treatment to dine-in (5%), takeaway (5%), delivery commissions (input VAT), staff meals (deemed supply treatment), wastage adjustments, and alcoholic beverages (5% VAT; note energy drinks 100% excise + 5% VAT, carbonated drinks 50% excise + 5% VAT), every transaction, every quarter."
      }, {
        "title": "Weekly Food Cost Dashboard", "description": "We set up real-time dashboards showing food cost %, gross margin, and labour cost % by outlet, updated weekly so you can make corrective decisions before the month is over."
      }, {
        "title": "Multi-Outlet VAT Filing, Done Right", "description": "We file your consolidated VAT return with correct outlet-level reconciliation, correct treatment of inter-outlet transfers, and full supporting schedules that stand up to an FTA desk review."
      }
    ], "lawTitle": "📋 UAE Laws & FTA Rules, Restaurants & F&B (Verified)", "laws": [
      "Dine-in, takeaway & most food & beverages: Standard rated, 5% VAT (UAE VAT Law Art. 3)", "Unprocessed basic food items: Zero-rated, specific Schedule 1 categories only, not all food", "Delivery platform commissions (Talabat, Noon, Deliveroo): 5% input VAT, fully reclaimable", "Staff meals provided free of charge: Deemed supply, output VAT required (FTA VATP005)", "Food wastage written off: Input VAT clawback required, must be documented", "Alcoholic beverages: 5% VAT standard rate + emirate-level municipality levy (up to 30% in Dubai licensed venues). NOTE: UAE federal Excise Tax does NOT apply to alcohol, excise applies to tobacco (100%), energy drinks (100%), carbonated drinks (50%), sweetened drinks (50%)", "Energy drinks: 100% Excise Tax + 5% VAT. Carbonated drinks (excl. plain water): 50% Excise Tax + 5% VAT. Sweetened drinks: 50% Excise Tax + 5% VAT", "Tourism Dirham (DTCM): NOT subject to VAT, collected as agent on behalf of authority", "Municipality fees (5–10%): NOT subject to VAT, government levy, pass-through only", "Tourist Tax Refund (TRF): NOT applicable to food & beverage, retail goods only", "Food imports (non-GCC): 5% customs duty + 5% VAT at point of import", "PEPPOL e-invoicing: Mandatory for B2B transactions, phased rollout from 2026"
    ], "storyTitle": "How BookLean Helped This Restaurant Owner, Real Story", "story": "When Rajan opened his second outlet in JBR, his accountant could not keep up with multi-location reconciliation. VAT returns were based on bank deposits, staff meals were not accounted for under the deemed supply rule, and he had no idea which outlet was profitable. Three months after joining BookLean, he had a real-time cost dashboard, correct VAT filings for both locations, and discovered that his Marina outlet was cross-subsidising JBR by AED 18,000 per month. He renegotiated his JBR supplier contracts and restructured the menu. Both outlets were cash-positive within 60 days. Clarity does that. BookLean does not just file your returns, we become the financial partner your restaurant actually needs to grow.", "cta": "Book a Free Restaurant Finance Review →"
  }, "ecommerce": {
    "tag": "Ecommerce & Amazon Sellers UAE · Verified UAE Tax Laws 2026", "title": "Ecommerce & Amazon Sellers, UAE VAT, FBA Obligations & Marketplace Accounting", "sub": "UAE ecommerce is one of the fastest-growing sectors in the region, but the VAT obligations are complex and widely misunderstood. Amazon FBA UAE, Noon, Shopify, and cross-border digital services each carry distinct UAE VAT treatment. Most UAE sellers are non-compliant without knowing it. BookLean specialises in marketplace accounting and UAE ecommerce tax compliance.", "pain": [
      {
        "title": "Marketplace Payouts Never Match Bank Deposits", "description": "Platform fees, FBA storage charges, return reversals, and currency conversion mean your bank deposits never match your Seller Central dashboard. Even a small monthly mismatch undetected across four VAT periods creates a material return error, and the FTA can cross-reference your data."
      }, {
        "title": "VAT on Electronic Services, Widely Misunderstood", "description": "Under UAE VAT Law Article 49, electronic services supplied to UAE consumers by overseas businesses are subject to UAE VAT, and the overseas supplier must register with the FTA. Many UAE-based ecommerce businesses also misclassify their supply type between goods, services, and digital supplies, applying the wrong rate as a result."
      }, {
        "title": "Import VAT Paid at Customs, Never Reclaimed", "description": "VAT paid at UAE customs on imported goods is reclaimable as input VAT, but only if your TRN is referenced on the customs declaration. Most ecommerce sellers pay import VAT every shipment and never reclaim it. This is real cash left with the FTA every single quarter."
      }, {
        "title": "No True Inventory Costing = No True Margin", "description": "Most online sellers track sales revenue but not true landed cost, purchase price, freight, customs duty, FBA storage, and return rate. Without proper COGS accounting, your stated margin is not your real margin, and pricing and sourcing decisions are made without accurate data."
      }
    ], "sol": [
      {
        "title": "Marketplace Payout Reconciliation", "description": "We reconcile Amazon Seller Central, Noon, and Shopify payouts to your UAE bank statement monthly, every fee, return, storage charge, and FX difference accounted for correctly in your books and VAT return."
      }, {
        "title": "Correct UAE VAT Treatment by Supply Type", "description": "We determine the correct VAT treatment for your specific supply, B2B goods, B2C goods, digital services, exports, and ensure your quarterly VAT returns reflect the right output VAT liability and input VAT recovery position."
      }, {
        "title": "Import VAT Reclaim, Every Quarter", "description": "We ensure your import declarations carry your TRN and reclaim every dirham of eligible input VAT on imported stock, with FTA-compliant customs documentation for every claim, every quarter."
      }, {
        "title": "Landed Cost COGS Accounting", "description": "We set up inventory accounting with true landed cost per unit, purchase price, freight, customs duty, import VAT, so your P&L shows your real margin per SKU, not just gross revenue minus supplier invoices."
      }
    ], "lawTitle": "📋 UAE Laws, Ecommerce & Amazon Sellers (Verified)", "laws": [
      "Supply of goods to UAE consumers: Standard rated, 5% VAT (UAE VAT Law Art. 3)", "Mandatory VAT registration: Taxable supplies exceeding AED 375,000 in any 12-month period", "Voluntary VAT registration: Available above AED 187,500, recommended for input VAT recovery", "Electronic services to UAE consumers (B2C): 5% UAE VAT, overseas supplier must register (Art. 49)", "B2B digital services to UAE VAT-registered businesses: Reverse charge applies, buyer accounts for VAT", "Export of goods outside UAE: Zero-rated, documentary proof of export required (Art. 30)", "Import VAT (5%) at UAE customs: Fully reclaimable, TRN must be referenced on import declaration", "Amazon FBA storage in UAE: Creates a fixed establishment, UAE VAT registration required", "Customs duty on non-GCC imports: Standard rate 5% (alcohol, tobacco significantly higher)", "UAE Corporate Tax at 9% on net business profit above AED 375,000 (Decree-Law 47/2022)", "PEPPOL e-invoicing: Mandatory for B2B tax invoices, phased rollout from 2026"
    ], "storyTitle": "How BookLean Helped This Ecommerce Seller, Real Story", "story": "Mia was selling AED 2.1M per year across Amazon UAE and Noon but had no clear picture of her actual profitability after platform fees, returns, and import costs. Her VAT returns were based on bank deposits, not gross marketplace revenue. Her import VAT had never been reclaimed across 18 months of shipments. BookLean set up automated marketplace reconciliation, corrected her VAT filing methodology, recovered AED 28,000 in import VAT she had been leaving with the FTA each quarter, and built a real-time COGS dashboard by SKU. She discontinued three unprofitable product lines within one quarter and reinvested in her top performers. Her net margin improved from 6% to 14% in four months. That is what proper ecommerce accounting looks like.", "cta": "Book a Free Ecommerce Finance Review →"
  }, "realestate": {
    "tag": "Real Estate & Construction Accounting UAE · Verified UAE Tax Laws 2026", "title": "Real Estate & Construction, Property VAT, DLD Fees & Project Accounting", "sub": "UAE real estate and construction carry some of the most complex VAT rules in the region. First supply, subsequent supply, commercial versus residential, bare land, each category has a completely different VAT treatment. Getting it wrong creates liability or permanently blocks input tax recovery. BookLean has handled VAT for UAE developers, main contractors, and subcontractors since 2018.", "pain": [
      {
        "title": "First vs Subsequent Supply, Developers Get This Wrong", "description": "The first supply of a newly built commercial building: 5% VAT. First supply of a new residential building: zero-rated. Any subsequent supply of residential property: exempt, meaning no VAT charged AND no input VAT recovery on any related costs. Most developers do not plan their portfolio VAT position upfront and lose significant recoverable input tax on mixed-use projects."
      }, {
        "title": "Retention Payments, VAT Timing Errors Are Common", "description": "Under UAE VAT Executive Regulations, VAT on construction retention payments becomes due at the earlier of the date of invoice or the date of payment. This is not at project completion or defects liability period end. Most contractors defer retention VAT to when cash is actually received, creating a systematic under-declaration of output VAT each period."
      }, {
        "title": "DLD Fee Included in VAT, A Direct Error", "description": "The Dubai Land Department transfer fee (4%) is a government fee under Dubai Law No. 4 of 2014. It is NOT a taxable supply and must NOT appear in your VAT return. Many transactions are incorrectly processed with VAT applied to the DLD fee, an error that is difficult to correct retroactively."
      }, {
        "title": "Project Cost Tracking Without Proper Costing", "description": "Construction projects span years, involve dozens of subcontractors, variation orders, and retention releases. Without project-level cost accounting, you cannot track real profitability, correctly allocate input VAT between taxable and exempt use, or provide the audit trail the FTA expects during a review."
      }
    ], "sol": [
      {
        "title": "Property VAT Structuring from Day One", "description": "Before a development project starts, we map the VAT treatment of every supply type, commercial units, residential units, mixed-use floors, and build the input VAT apportionment model that maximises legitimate recovery from the outset."
      }, {
        "title": "Correct Retention VAT Timing", "description": "We track retention invoices and payments and declare VAT at the correct tax point, the earlier of invoice date or payment date, so your VAT returns always reflect the legally correct position, not a cash-basis approximation."
      }, {
        "title": "Project-Level Cost Accounting", "description": "We set up project accounting with cost codes for every contractor, variation, and material category, giving you real-time profitability per project and the correct VAT input allocation between taxable and exempt use for partial exemption purposes."
      }, {
        "title": "Input VAT Apportionment Calculation", "description": "For mixed-use developments, we calculate and apply the FTA-accepted partial exemption method each quarter, ensuring you recover the maximum allowable input VAT on shared costs such as design, infrastructure, and professional fees."
      }
    ], "lawTitle": "📋 UAE Laws, Real Estate & Construction (Verified)", "laws": [
      "First supply of new commercial building: Standard rated, 5% VAT (UAE VAT Law Art. 45)", "First supply of new residential building (within 3 years of completion): Zero-rated, input VAT fully recoverable (Cabinet Decision 52/2017, Sch. 3)", "Subsequent supply of residential property: Exempt, NO VAT charged, NO input VAT recovery (Art. 46)", "Bare undeveloped land: Exempt from VAT, not a taxable supply", "Commercial real estate rental: Standard rated, 5% VAT", "Residential property long-term rental: Exempt from VAT (Cabinet Decision 52/2017)", "Construction services: Standard rated, 5% VAT (Art. 3)", "DLD transfer fee (4% in Dubai): NOT subject to VAT, government fee (Dubai Law No. 4/2014)", "Retention payment VAT tax point: Earlier of invoice date or payment date (Art. 25, Exec. Reg.)", "Off-plan sales instalments: VAT due at each instalment payment, not at handover", "Mixed-use development: Partial exemption required, apportion input VAT by taxable vs exempt use", "UAE Corporate Tax at 9% on trading profits above AED 375,000 (Decree-Law 47/2022)"
    ], "storyTitle": "How BookLean Helped This Real Estate Developer, Real Story", "story": "A UAE property developer approached BookLean mid-project having applied 5% VAT on all units in a mixed residential-commercial development. The residential units on first supply should have been zero-rated, not standard rated. BookLean identified AED 340,000 in incorrectly charged output VAT, filed voluntary disclosures with the FTA, issued corrected tax invoices to buyers, and rebuilt the input VAT apportionment model, recovering AED 180,000 in input tax that had never been claimed on shared infrastructure costs. The FTA accepted the voluntary disclosures without penalties. The lesson: VAT planning before a development begins is not optional, it determines your actual project margin. Once units are sold at the wrong VAT rate, the correction is costly and time-consuming.", "cta": "Book a Free Property Finance Review →"
  }, "healthcare": {
    "tag": "Healthcare & Clinics Accounting UAE · Verified UAE Tax Laws 2026", "title": "Healthcare & Clinics, Zero-Rated Services, Cosmetic VAT & Insurance Billing", "sub": "UAE healthcare VAT has three categories, zero-rated, standard-rated (5%), and exempt, and the boundary between them is not always clear. Most clinics are either charging VAT on zero-rated services, claiming input VAT they are not entitled to, or both. BookLean specialises in UAE healthcare accounting for DHA, DOH, and MOH-licensed facilities across Dubai and Abu Dhabi.", "pain": [
      {
        "title": "Charging 5% VAT on Zero-Rated Medical Services", "description": "Under Cabinet Decision No. 52 of 2017 (Schedule 3), preventive and curative healthcare services supplied by a licensed healthcare provider are zero-rated, not 5%. Many clinics apply 5% across all consultations and procedures, overcharging patients and overstating output VAT on their returns. Both need to be corrected, and the patient correction is the harder one."
      }, {
        "title": "Cosmetic vs Medical, Documentation Is Everything", "description": "A cosmetic rhinoplasty: 5% VAT. The same procedure to correct a deviated septum with documented breathing impairment: zero-rated as a curative supply. The law does not draw a bright line, clinical documentation supporting medical necessity is what determines the VAT treatment. Most clinics do not have this documentation framework in place."
      }, {
        "title": "Employee Health Insurance, Input VAT Claimed Incorrectly", "description": "Under Article 53 of the UAE VAT Executive Regulations, input VAT on employee health insurance premiums is specifically blocked from recovery. This is one of the most commonly misunderstood blocked input VAT categories, many clinics and businesses claim it routinely, creating a liability discovered only at audit."
      }, {
        "title": "Insurance Billing Reconciliation, Revenue Distorted", "description": "Insurance claim submissions, partial approvals, co-payment splits, rejections, and resubmissions create a reconciliation challenge that most clinic accounting systems cannot handle without specialist configuration. Without clean reconciliation, VAT returns are based on incorrect revenue figures, an automatic FTA audit risk."
      }
    ], "sol": [
      {
        "title": "Service Classification Framework", "description": "We build a documented VAT classification matrix for every service your clinic provides, zero-rated preventive/curative, standard-rated cosmetic/elective, out-of-scope government fees, with clinical criteria and FTA guidance references for each. Audit-ready from day one."
      }, {
        "title": "Insurance Reconciliation, Clean Monthly", "description": "We reconcile insurance claims, approvals, co-pays, rejections, and resubmissions against your PMS and accounting system every month. Your VAT return is always based on actual collected revenue, not billed amounts or bank receipts alone."
      }, {
        "title": "Partial Exemption Calculation", "description": "For clinics providing both zero-rated medical and standard-rated cosmetic services, we calculate the correct input VAT recovery ratio every quarter and perform the required annual adjustment, so you recover exactly what you are entitled to, and nothing more."
      }, {
        "title": "Medical Equipment Import VAT Reclaim", "description": "Approved medical equipment and pharmaceuticals imported from overseas attract import VAT at customs, and it is reclaimable. We ensure every import declaration references your TRN and that all eligible input VAT claims are captured in your quarterly return."
      }
    ], "lawTitle": "📋 UAE Laws, Healthcare & Clinics (Verified)", "laws": [
      "Preventive & curative healthcare by licensed facility: Zero-rated, 0% VAT (Cabinet Dec. 52/2017, Sch. 3)", "Cosmetic & elective procedures (not medically necessary): Standard rated, 5% VAT", "Approved human medicines: Zero-rated (FTA Taxable Goods and Services Guide)", "Approved medical equipment: Zero-rated (FTA Taxable Goods and Services Guide)", "Non-approved supplements, general wellness products: Standard rated, 5% VAT", "Patient co-payment: Same VAT rate as the underlying medical service supplied", "Employee health insurance premiums: Input VAT BLOCKED, NOT reclaimable (Art. 53, Exec. Reg.)", "DHA, DOH, MOH licence and regulatory fees: Outside scope of VAT, government fees", "Services by unlicensed provider: Standard rated, zero-rating requires valid licence", "Mixed services clinic (medical + cosmetic): Partial exemption, input VAT apportionment required", "UAE Corporate Tax at 9% on clinic net profit above AED 375,000 (Decree-Law 47/2022)"
    ], "storyTitle": "How BookLean Helped This Clinic, Real Story", "story": "A multi-specialty clinic in Dubai Healthcare City had been applying 5% VAT to all services for 14 months, including zero-rated GP consultations, diagnostic tests, and physiotherapy sessions. BookLean's review identified AED 164,000 in incorrectly collected output VAT and AED 38,000 in input VAT incorrectly claimed on employee health insurance premiums. We filed voluntary disclosures with the FTA, issued corrected tax invoices to patients as credit notes, rebuilt the billing system with correct VAT codes per service, and restructured the insurance reconciliation process. The FTA accepted all disclosures. No penalties were issued. Getting healthcare VAT right from the start matters, the cost of corrections is high, and the reputational risk with patients even higher.", "cta": "Book a Free Healthcare Finance Review →"
  }, "tech": {
    "tag": "Technology & SaaS Startup Accounting UAE · 2026", "title": "Technology & SaaS Startups, Investor-Ready Financials & UAE Tax Structuring", "sub": "UAE tech startups need more than bookkeeping. They need IFRS-compliant financials, correct SaaS revenue recognition, a correctly structured entity, and a clear UAE Corporate Tax position before a due diligence team arrives. BookLean has helped UAE startups close angel rounds and Series A raises with financial statements that pass investor scrutiny.", "pain": [
      {
        "title": "Investor Due Diligence Fails, Messy Books Kill Deals", "description": "Most UAE startup founders focus on product and growth and discover, when an investor requests financial statements, that they have 18 months of unreconciled bank transactions, no revenue recognition policy, and a spreadsheet. Clean books close rounds. Messy books lose them. We have seen both outcomes."
      }, {
        "title": "SaaS Revenue Recognition Is Complex", "description": "Under IFRS 15, SaaS subscription revenue must be recognised over the service period, not on receipt of cash. Annual subscriptions collected upfront create deferred revenue. Multi-element arrangements (software + implementation + support) require revenue allocation. Standard bookkeeping software without specialist configuration gets this wrong consistently."
      }, {
        "title": "Free Zone 0% CT, Most Startups Do Not Actually Qualify", "description": "Free zone companies qualify for 0% Corporate Tax as a Qualifying Free Zone Person (QFZP) only if they earn qualifying income exclusively and maintain genuine economic substance. A UAE startup with paying UAE mainland customers almost certainly earns non-qualifying income. If this exceeds 5% of total revenue or AED 5 million, the entire entity is taxed at 9% on all income for that year."
      }, {
        "title": "ESOP Accounting Ignored Until Due Diligence", "description": "Employee share options and phantom equity create share-based payment expenses under IFRS 2 that must be recognised in the P&L. Most UAE startups issue options with no accounting entries at all, creating a restatement risk that surfaces exactly when an investor runs due diligence. Not the right moment to discover a material accounting adjustment."
      }
    ], "sol": [
      {
        "title": "Investor-Ready Financials from Month One", "description": "We set up your chart of accounts, revenue recognition policy, and monthly close process from day one, so when an investor requests 18 months of financials, you send them in 48 hours, not six weeks."
      }, {
        "title": "IFRS 15 Revenue Recognition for SaaS", "description": "We configure your accounting system to correctly recognise subscription revenue over the service period, defer upfront annual payments as deferred revenue, and allocate multi-element arrangements correctly, IFRS 15 compliant from the start."
      }, {
        "title": "QFZP Eligibility Assessment & CT Structuring", "description": "We assess your actual qualifying income percentage based on your specific revenue streams, advise on the most tax-efficient UAE entity structure for your business model, and handle Corporate Tax registration and annual filing."
      }, {
        "title": "Virtual CFO for Fundraising", "description": "We prepare investor data rooms, financial models, board reports, and cap table analysis, acting as your outsourced CFO through the fundraising process without the cost of a full-time senior hire."
      }
    ], "lawTitle": "📋 UAE Laws, Technology & SaaS Startups (Verified)", "laws": [
      "B2B SaaS to UAE-registered businesses: Standard rated, 5% VAT (UAE VAT Law Art. 3)", "B2C electronic/digital services to UAE consumers: 5% VAT, overseas supplier must register (Art. 49)", "Free zone company: 0% CT only if QFZP, qualifying income only, genuine substance required", "Non-qualifying income exceeding 5% of revenue OR AED 5M: Entire entity taxed at 9% on all income", "UAE CT Small Business Relief: Revenue below AED 3M, elect 0% CT (valid to 31 Dec 2026)", "Tax Group formation: Available under UAE CT for commonly-owned UAE entities (Art. 40)", "Transfer pricing: Related party transactions must be at arm's length, documentation required", "R&D expenditure: Expensed or capitalised, affects taxable income; R&D tax credits available", "ESOP/VSOP: Share-based payment expense, IFRS 2 accounting required", "DIFC/ADGM entities: Separate regulatory regime under DFSA/FSRA, different CT treatment", "PEPPOL e-invoicing: Mandatory for B2B tax invoices, phased rollout from 2026"
    ], "storyTitle": "How BookLean Helped This UAE Startup, Real Story", "story": "Ahmed's SaaS company was 18 months old and closing a Series A when his lead investor requested IFRS-compliant financial statements for the prior two years. He had a spreadsheet. BookLean reconstructed 20 months of records from bank statements and payment processor exports, implemented IFRS 15 revenue recognition with correct deferred revenue accounting, produced two-year comparative financial statements, and prepared the complete investor data room, in five weeks. Ahmed closed the round. That is what being investor-ready actually means, and it starts on month one, not month 18.", "cta": "Book a Free Startup Finance Review →"
  }, "retail": {
    "tag": "Retail & Consumer Brands Accounting UAE · Verified UAE Tax Laws 2026", "title": "Retail & Consumer Brands, Inventory Accounting, VAT on Promotions & TRF Compliance", "sub": "UAE retail means managing VAT across in-store, online, and marketplace channels simultaneously. Promotional discounts, gift cards, stock write-offs, and the Tourist Tax Refund scheme all carry specific VAT rules under UAE law that most retailers handle incorrectly. BookLean has handled retail accounting from single-store boutiques to multi-emirate chains.", "pain": [
      {
        "title": "VAT on Discounts, Paying Tax on Money Not Collected", "description": "Under UAE VAT Executive Regulations Article 28, VAT applies to the discounted amount actually charged to the customer, not the original list price. Many retailers issue invoices at full price and apply discounts in the POS without reflecting them on the tax invoice, meaning they declare and pay VAT on revenue they never actually collected."
      }, {
        "title": "Gift Cards, VAT Deferred to Redemption, Not Sale", "description": "Under the FTA Vouchers Guide, VAT on gift cards and vouchers is due at the point of redemption, not when the card is sold. Most retailers account for gift card VAT at point of sale, creating a systematic overpayment that accumulates every quarter."
      }, {
        "title": "Stock Write-Offs, VAT Adjustment Ignored", "description": "When goods are written off as damage or wastage, the input VAT originally claimed on purchasing those goods must be adjusted. When goods are stolen, the input VAT clawback is NOT required, but the theft must be properly documented. Most retailers write off stock with no VAT adjustment of any kind, creating a liability that builds over time."
      }, {
        "title": "Tourist Tax Refund, Not Set Up for Eligible Retailers", "description": "The UAE TRF scheme allows tourists to reclaim VAT on retail purchases of goods, clothing, electronics, jewellery, and similar, at qualifying UAE retailers registered with Planet Payment. Many eligible UAE retailers are not registered and their international customers are asking for TRF receipts that cannot be issued."
      }
    ], "sol": [
      {
        "title": "Correct VAT on Every Promotion Type", "description": "We configure your billing system to apply UAE VAT correctly on every promotion, discounts, buy-one-get-one, free gifts with purchase, loyalty point redemptions, and gift cards, with correct tax invoice formats for each scenario."
      }, {
        "title": "Gift Card Revenue Recognition & VAT", "description": "We set up deferred revenue accounting for gift card sales and apply VAT correctly at redemption, not at sale, so your VAT return, revenue recognition, and financial statements are all correct and consistent."
      }, {
        "title": "Stock Write-Off VAT Adjustments", "description": "We process monthly write-offs with the correct VAT treatment, input VAT adjustment for wastage and damage, documentation protocol for theft (where input VAT clawback is not required), so your VAT return reflects your actual stock position correctly."
      }, {
        "title": "Tourist Refund Scheme Registration", "description": "We register your retail outlets with Planet Payment for the UAE TRF scheme and configure your POS to issue compliant TRF tax invoices, opening your business to international tourist VAT refund claims on eligible retail purchases."
      }
    ], "lawTitle": "📋 UAE Laws, Retail & Consumer Brands (Verified)", "laws": [
      "Standard retail goods supplied in UAE: Standard rated, 5% VAT (UAE VAT Law Art. 3)", "Promotional discounts: VAT applies to actual discounted amount charged, not list price (Art. 28, Exec. Reg.)", "Gift cards & vouchers: VAT due at redemption, not at point of sale (FTA Vouchers Public Clarification)", "Stock written off as wastage/damage: Input VAT adjustment required, clawback applies", "Stock written off as theft: Input VAT clawback NOT required, must be evidenced as theft", "Tourist Tax Refund (TRF): Available on retail goods (clothing, electronics, jewellery), minimum AED 250", "TRF: NOT applicable to food & beverage, services, or consumables", "TRF: Planet Payment registration required, specific POS invoice format mandatory", "Import duty on non-GCC goods: 5% standard rate (alcohol/tobacco significantly higher)", "Import VAT (5%) at UAE customs: Fully reclaimable, TRN must appear on customs declaration", "Input VAT on store fit-out, fixtures, signage: Fully reclaimable as business expenses", "UAE Corporate Tax at 9% on net profit above AED 375,000 (Decree-Law 47/2022)"
    ], "storyTitle": "How BookLean Helped This Retailer, Real Story", "story": "A fashion retailer with four locations across Dubai and Abu Dhabi came to BookLean after the FTA issued a desk review notice querying their input VAT claims. Their previous accountant had been applying input VAT clawback to stock stolen from stores, which is not required under UAE VAT law when theft is properly documented. They had also been issuing full-price VAT invoices for discounted sales and paying VAT on the original list price rather than the discounted amount actually charged. BookLean corrected both positions through voluntary disclosures, recovered AED 22,000 in legitimately structured input VAT that had been missed, reconfigured the POS to generate correct UAE VAT invoices for every transaction type, and registered them for the Tourist Tax Refund scheme. The FTA desk review closed without penalties or additional assessments.", "cta": "Book a Free Retail Finance Review →"
  }, "hospitality": {
    "tag": "Hospitality & Tourism Accounting UAE · Verified UAE Tax Laws 2026", "title": "Hospitality & Tourism, Revenue VAT, Tourism Dirham & OTA Compliance", "sub": "Hotels, holiday homes, and tour operators in UAE face a unique combination of tax obligations, VAT on room revenue calculated on the gross amount, Tourism Dirham and municipality fees that are specifically not VATable, OTA commissions with their own input VAT treatment, and short-term versus long-term rental rules that change everything. BookLean understands the full hospitality accounting stack from PMS to FTA return.", "pain": [
      {
        "title": "OTA Commissions, VAT on Net Payout Is Wrong", "description": "When Booking.com or Expedia deducts its commission before paying out, your bank receives the net amount. But UAE VAT is due on the full room rate charged to the guest, the gross amount, not on the net payout after OTA commission. Hotels that declare output VAT based on bank receipts systematically understate their VAT liability every quarter."
      }, {
        "title": "Tourism Dirham Included in VATable Revenue", "description": "The Dubai Tourism Dirham (AED 7–20 per room per night by hotel category) is collected by hotels on behalf of DTCM. It is not the hotel's income. It is NOT subject to VAT and must NOT be included in the VAT return as taxable turnover. Many hotels include it, overpaying VAT consistently with no easy mechanism to recover the overpayment."
      }, {
        "title": "Short-Term vs Long-Term Rental, VAT Changes", "description": "Short-term accommodation (under 30 consecutive days): 5% VAT standard rated. Residential accommodation under a long-term contract (30 days or more, residential purpose): Exempt from VAT. When hotels convert rooms to long-term leases, the VAT treatment changes completely, and so does the input VAT recovery position on costs relating to those rooms."
      }
    ], "sol": [
      {
        "title": "Gross Revenue VAT Reporting", "description": "We configure your revenue accounting to declare output VAT on gross room revenue, including the portion paid by OTAs as commission, and separately claim OTA commission as input VAT. Your return correctly reflects both sides of the transaction."
      }, {
        "title": "Tourism Dirham & Municipality Fee Segregation", "description": "We correctly classify Tourism Dirham and municipality fee collections as pass-through liabilities, outside your VATable turnover, and ensure they are reported separately and never included in output VAT calculations."
      }, {
        "title": "Holiday Home VAT Compliance", "description": "We register holiday home operators for VAT, set up correct invoice templates, and ensure monthly VAT accounting matches your property management system, whether you manage one unit or a portfolio of fifty."
      }, {
        "title": "PMS-to-Accounts Reconciliation", "description": "We reconcile your Property Management System revenue reports against bank statements and accounting records monthly, with full explanation of every OTA settlement, Tourism Dirham collection, municipality fee, and long-term vs short-term booking split."
      }
    ], "lawTitle": "📋 UAE Laws, Hospitality & Tourism (Verified)", "laws": [
      "Short-term accommodation (under 30 consecutive days): Standard rated, 5% VAT (UAE VAT Law Art. 3)", "Long-term residential rental (30+ days, residential purpose): Exempt from VAT (Cabinet Dec. 52/2017)", "Output VAT on room revenue: Based on GROSS amount charged to guest, not net after OTA commission", "OTA commissions (Booking.com, Expedia, Airbnb): 5% input VAT charged to hotel, fully reclaimable", "Dubai Tourism Dirham (DTCM fee): NOT subject to VAT, collected as agent (AED 7–20/room/night)", "Municipality fee (10% in Dubai): NOT subject to VAT, government levy, pass-through only", "Food & beverage within hotel: Standard rated, 5% VAT", "Holiday home short-term rental: Same VAT treatment as hotel, 5% on gross booking amount", "Mandatory VAT registration: Taxable supplies above AED 375,000/year, AED 20,000 late penalty", "Tourist Tax Refund (TRF): NOT applicable to accommodation or F&B, retail goods only", "UAE Corporate Tax at 9% on hospitality profits above AED 375,000 (Decree-Law 47/2022)"
    ], "storyTitle": "How BookLean Helped This Hotel Group, Real Story", "story": "A boutique hotel group with three properties in Dubai Marina came to BookLean after an internal review found a AED 95,000 discrepancy between declared output VAT and PMS revenue. The cause: output VAT had been declared on net OTA payouts instead of gross room rates, and Tourism Dirham collections had been incorrectly included in taxable turnover. Both errors had been compounding each quarter. BookLean filed corrected VAT returns with full PMS reconciliation schedules, claimed input VAT on OTA commissions that had never been recovered, excluded Tourism Dirham from taxable turnover in all corrected periods, and restructured the monthly accounting process to prevent recurrence. The FTA accepted all corrections. The hotel group recovered a net AED 42,000 in VAT overpayments. These are not edge cases, they are the standard errors we find in UAE hospitality accounting.", "cta": "Book a Free Hospitality Finance Review →"
  }, "freelancer": {
    "tag": "Freelancer & Sole Establishment Accounting UAE · 2026", "title": "Freelancers & Sole Establishments, UAE Corporate Tax, VAT & Structure", "sub": "Freelancing in UAE is growing rapidly, but most freelancers do not realise they are operating as a business under UAE law, and the compliance obligations are real, immediate, and penalised without warning. UAE Corporate Tax registration is mandatory regardless of profit level. VAT registration is mandatory above AED 375,000 annual taxable turnover. Penalties begin on day one of non-compliance.", "pain": [
      {
        "title": "Corporate Tax Registration, Missed, Then Penalised", "description": "Under Federal Decree-Law No. 47 of 2022, every UAE business, including freelancers, sole establishments, and individual licence holders, must register for Corporate Tax with the FTA regardless of income level. The penalty for failing to register by the required deadline is AED 10,000. Most freelancers discover this obligation only when the penalty notice arrives."
      }, {
        "title": "Personal & Business Expenses Mixed, CT Deductibility at Risk", "description": "Under Article 28 of the UAE CT Law, expenses are only deductible if they are incurred wholly and exclusively for the purposes of the business. When personal expenses go through the same bank account as business income, which is the default for most UAE freelancers, every personal transaction becomes a CT audit risk, and your real deductible expenses are buried inside mixed transactions."
      }, {
        "title": "VAT Registration Threshold Crossed Unknowingly", "description": "Many UAE freelancers cross the AED 375,000 mandatory VAT registration threshold in year two or three of their business without realising it. The obligation arises at the end of any 12-month rolling period in which taxable turnover exceeded AED 375,000. The penalty for late registration is a fixed AED 20,000. The FTA has the data to identify unregistered businesses operating above threshold."
      }, {
        "title": "Freelance Permit vs Sole Establishment, Wrong Structure Chosen", "description": "A freelance permit allows an individual to work in specified activities under their own name, it is personal, activity-restricted, and different from a trade licence. A sole establishment is a separate legal entity under DED with its own trade licence. The two have different banking implications, different VAT registration pathways, and different CT filing obligations. Many freelancers operate under the wrong structure for their actual activity and client base."
      }
    ], "sol": [
      {
        "title": "CT Registration, Done Immediately", "description": "We register you for UAE Corporate Tax with the FTA, assess your eligibility for Small Business Relief (0% CT on revenue below AED 3M for periods to 31 Dec 2026), and file your annual CT return, so you are always compliant and never exposed to the AED 10,000 late registration penalty."
      }, {
        "title": "Clean Monthly Bookkeeping", "description": "We set up a dedicated business account structure, implement monthly bookkeeping that separates business and personal expenses cleanly, and produce monthly P&L statements, so your deductible expenses are clear, documented, and defensible."
      }, {
        "title": "VAT Monitoring & Registration", "description": "We track your rolling 12-month taxable turnover every quarter. When you approach the AED 375,000 mandatory threshold, or the AED 187,500 voluntary threshold where registration is beneficial for input VAT recovery, we advise you in time and register you before the deadline."
      }, {
        "title": "Structure Advisory", "description": "We advise on the correct legal structure for your specific freelance activity, client base, and growth plans, freelance permit, sole establishment, or LLC, and handle the registration, bank account opening, and all compliance filings from day one."
      }
    ], "lawTitle": "📋 UAE Laws, Freelancers & Sole Establishments (Verified)", "laws": [
      "CT registration: Mandatory for ALL UAE businesses including freelancers, penalty AED 10,000 (Art. 51, CT Law)", "CT rate: 9% on taxable income above AED 375,000 (Federal Decree-Law No. 47 of 2022)", "Small Business Relief: Revenue below AED 3M, elect 0% CT, valid for tax periods to 31 Dec 2026", "Mandatory VAT registration: Taxable turnover exceeding AED 375,000 in any 12-month period", "Late VAT registration penalty: Fixed AED 20,000 (UAE VAT Law Administrative Penalties Schedule)", "Voluntary VAT registration: Available above AED 187,500 taxable turnover, recommended for input VAT recovery", "Deductible expenses: Must be wholly and exclusively incurred for business purposes (Art. 28, CT Law)", "Entertainment expenses: Capped at 50% deductibility (Art. 32, CT Law)", "Fines & penalties: NOT deductible under UAE CT Law", "Freelance permit vs sole establishment: Different legal status, banking, and CT registration pathway", "WPS (Wage Protection System): Required for employees on UAE work visas, NOT required for sole owners", "Employee gratuity: 21 days basic salary per year for first 5 years, 30 days per year thereafter, capped at 2 years basic salary (Federal Decree-Law No. 33/2021, Art. 51). Must be paid within 14 days of contract end."
    ], "storyTitle": "How BookLean Helped This Freelancer, Real Story", "story": "Amira is a UX designer with a TECOM freelance permit. In her second year she earned AED 480,000, and like many UAE freelancers, she assumed there was no tax in UAE. In month 16, two FTA penalty notices arrived: AED 10,000 for failing to register for Corporate Tax, and AED 20,000 for failing to register for VAT after crossing the AED 375,000 mandatory threshold. Total penalties before any tax: AED 30,000. BookLean registered her for both immediately, elected Small Business Relief on the CT return (zero tax owed on her income level), filed a backdated VAT return for the period since the threshold was crossed, and submitted penalty reconsideration applications for both notices with supporting documentation. Both penalties were reduced. Total saved: AED 18,000. The cost of compliance is always lower than the cost of non-compliance, and it starts on day one, not when the penalty arrives.", "cta": "Book a Free Freelancer Finance Review →"
  }
};
